### ISSUE TITLE
Swtches active tab to target tab on selection

### ISSUE THREAD

**Issue by pallaswept** [l10nelw/select-tabs#3]
Hi, and thanks for a handy addon :)

I just have one small issue. When I rightclick a tab, which I am not currently viewing, and use this addon to select tabs, it will switch me to the target tab. I don't want to change to that tab, I just want to select it. Could this be fixed?

To explain why this matters: The main reason I am using this addon, is to select groups of tabs which are using lot of resources (usually, RAM) and then use another addon to suspend(discard) those tabs. But now, when I select the tabs, it changes to the 'target' tab, rather than just selecting it, so now I can suspend all of the other selected tabs, but I cannot suspend this one because it's the open tab, so I have to:

1. Right click 'target' tab
2. Select all tabs from same site
3. Suspend selected tabs
4. Change back to the tab I started from
5. Suspend the 'target' tab

What I would like to do is:

1. Right click 'target' tab
2. Select all tabs from same site
3. Suspend selected tabs

The description on AMO says, "A simple tool for doing one thing very well: select multiple related tabs in the current window." but really, it does two things: "select multiple related tabs in the current window, _and then switch to one of them_" I hope you might be able to adjust this behaviour so it's just selecting, and not changing tabs. Thank you very much in advance!

**Comment by l10nelw** [comment]
Thanks for bringing up your issue! What's going on is that if the current tab does not match a chosen selection's criteria, the tab would of course not be included in the selection - that's it.

I think to resolve this, I will add an "Always include current tab" toggle in settings, and also an on-the-spot toggle in the form of a <kbd>Shift</kbd>+click command.

**Comment by pallaswept** [comment]
Thanks for looking into this for me. I'm not sure I explained myself properly though. My intention here is not to select the current tab, nut, to keep the current tab as the current tab, instead of the current behaviour, which is to change the current tab to the target tab. I'll try to give a more specific example, with screenshots for illustration -  I'm not great with words, I apologise!

Let's say I have lots of github tabs open, and I also have one other tab, which I'm using at the time. I know I'm not going to need all those github tabs, and they are using lots of RAM, so I want to use another addon to suspend them - but first, I need to select them all. So I right-click one, and scroll down to your addon's menu, and select 'Same site', intending to select all of the github tabs, like so:

![image](https://github.com/l10nelw/select-tabs/assets/132128962/41ee5d17-ef60-4784-934e-e97fd5f42ee3)


But I want to stay on the tab I'm using right now, when I select all those github tabs, because, I'm using that tab, and especially because, I can't suspend the github tab if it is the current tab -so I want to select it, but *not* change to it. But when I select it as per the above screenshot, as soon as I click 'Same site', this is what happens:

![image](https://github.com/l10nelw/select-tabs/assets/132128962/c568aba7-a9e3-4af6-a843-4500e97b6b29)

So now, not only have I selected the tab (and all others from the same site), I have also changed to it. I hope to be able to select tabs based on a target tab, without changing to the target tab.

Apologies for causing confusion about the request here. I hope you can help!

**Comment by pallaswept** [comment]
BTW, I have a feeling this may be a limitation of firefox - because I cannot even manually show you the intended effect, where all the github tabs are selected, but the "page I'm using right now" is *not* selected, but *is* active. So, it seems like firefox will not allow the currently active tab to be un-selected while other tabs are selected.

**Comment by l10nelw** [comment]
> the "page I'm using right now" is not selected, but is active

Not possible; an active tab is always selected (aka highlighted, as it's internally called). If there are multiple tabs selected, the active tab is always a member of that selection set. I believe this is consistent among all browsers, not just firefox.

Conveniently, a tab suspend operation works on all tabs in a selection except the active one. For use cases like this, it could be useful to have a way to maintain an active tab's state when invoking a selection command, which I am working on.

**Comment by pallaswept** [comment]
It sounds like an impossible task, but it also sounds like you have some clever idea :) Thanks for any help you can offer, but I understand there is a limitation of the browser, so I will leave it open for you to try out your idea, but please feel free to close this case whenever you see fit. Thanks very much!

**Comment by l10nelw** [comment]
@pallaswept There is an alternative solution to consider. You should check if your tab discard addon can be configured to switch away to another tab when it discards the current tab. I use Auto Tab Discard and it does that. Also I think it switches to the nearest loaded tab, which often happens to be the previously current tab.

**Comment by pallaswept** [comment]
> @pallaswept There is an alternative solution to consider. You should check if your tab discard addon can be configured to switch away to another tab when it discards the current tab. I use Auto Tab Discard and it does that. Also I think it switches to the nearest loaded tab, which often happens to be the previously current tab.

Thanks for that tip, I also use ATD so I should be able to make use of it. I do have other use-cases in mind too though, like closing all the tabs, and in that sort of case I don't think there's anything this addon can do - however I also use the 'Select After Closing Current' addon, so that should cover that use-case. Then there are mass-reloads.... But, it's OK....I think that whatever the scenario, there will be workarounds if I need them :) It's a shame the browsers never considered the utility of selecting tabs without viewing them, but, I'll survive :laughing:

**Comment by l10nelw** [comment]
Alright. Since the clear solution lies elsewhere without needing anything new, I'll abandon the "include current tab" idea to avoid adding unnecessary complexity. Cheers
