### ISSUE TITLE
Feature Suggestions - Slight Tweaks to "Add One Left" and "Add One Right" + One additional Keyboard Shortcut

### ISSUE THREAD

**Issue by Cr8zyIvan** [l10nelw/select-tabs#5]
I really appreciate the "Directional: Add One Left / Add One Right" Keyboard Shortcuts. While I have suggestions, I cannot say they are 100% thought out fully.

The tweaks to behavior I envisage for these two Keyboard Shortcuts would be:

**Shifting the Active Tab:**
- While Adding One to the Left or to the Right, the Active Tab would change (or switch) to the newly added Tab, rather than the Active Tab remain unchanged. e.g. I Add a Tab to the Left. The Leftwards Tab that was added now becomes the active Tab, while "leaving a trail of selected Tabs behind".
**Incrementally Deselecting Tabs:**
- If I have 5 Tabs in my selection, while I've been adding selections in the Leftwards direction, If I then chose to "Select Tabs" in the Rightwards direction, this would "Deselect Tabs" in the Rightwards direction instead. Once I've deselected all but the last remaining Tab (all while shifting the Active Tab to the Right, while I'm Deselecting), then the "Add One Right" would start adding Tabs to the Right, while "leaving a trail of selected Tabs behind".

Suggesting one additional Keyboard Shortcut:

**Selecting All Tabs:**
- One other Keyboard Shortcut I would love to see added as well is one that Selects All the Tabs (while keeping the Active Tab unchanged).

Please feel free to let me know if my suggestions and explanations are unclear. I am unsure myself if they are.

Thank you for your Extension, which I use almost every day. Cheers!

**Comment by l10nelw** [comment]
Hi @Cr8zyIvan. 

Shifting the active tab left/right while growing/shrinking a selection "trail" will come very soon...

"Select All Tabs" is a native tab context menu command (if you didn't [remove it](https://github.com/l10nelw/select-tabs/wiki/How-to-remove-the-Close-Multiple-Tabs-and-Select-All-Tabs-commands-from-Firefox's-tab-context-menu)). Does that work for you?

**Comment by l10nelw** [comment]
Latest version is ready 🥳

**Comment by Cr8zyIvan** [comment]
It took me a while to see it, but I just saw the new update. Wow!

Not only that, you ADDED the "Trail Left" and "Trail Right", where my thoughts were about replacing the "Add Left" and "Add Right". It's so Simple and it's Perfect.

Thank you! 🙏
